// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgTnfdweKISfxzYi6KRRJ_fyt-sT20veo',
    appId: '1:376648942084:web:4582b8edfc8a8a6a5a6b51',
    messagingSenderId: '376648942084',
    projectId: 'chat-app-8dc9c',
    authDomain: 'chat-app-8dc9c.firebaseapp.com',
    storageBucket: 'chat-app-8dc9c.firebasestorage.app',
    measurementId: 'G-GLSC8X8CM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5dD3_ip-oKnmw95EnKfEsow2SwQ0G4xU',
    appId: '1:376648942084:android:e54835831ae119895a6b51',
    messagingSenderId: '376648942084',
    projectId: 'chat-app-8dc9c',
    storageBucket: 'chat-app-8dc9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnyRHaS0KB7_VAFxoQLh5FW8TEK-a-MIg',
    appId: '1:376648942084:ios:6ebe73699d4d0dcc5a6b51',
    messagingSenderId: '376648942084',
    projectId: 'chat-app-8dc9c',
    storageBucket: 'chat-app-8dc9c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnyRHaS0KB7_VAFxoQLh5FW8TEK-a-MIg',
    appId: '1:376648942084:ios:6ebe73699d4d0dcc5a6b51',
    messagingSenderId: '376648942084',
    projectId: 'chat-app-8dc9c',
    storageBucket: 'chat-app-8dc9c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgTnfdweKISfxzYi6KRRJ_fyt-sT20veo',
    appId: '1:376648942084:web:0165263c7ad628ab5a6b51',
    messagingSenderId: '376648942084',
    projectId: 'chat-app-8dc9c',
    authDomain: 'chat-app-8dc9c.firebaseapp.com',
    storageBucket: 'chat-app-8dc9c.firebasestorage.app',
    measurementId: 'G-XPRMFHBDMR',
  );
}
